import { Building2, CheckCircle2, Database, Layers3, Unplug } from "lucide-react";
import { PageShell } from "../../components/app/page-shell"; import { PageHeader } from "../../components/app/page-header"; import { DataTable, Panel, StatusBadge } from "../../components/app/ui";
import { volunteerCustomHomes } from "../../data/volunteer-custom-homes"; import { volunteerCustomHomesGLAccounts } from "../../data/gl-accounts"; import { compassReportingCategories } from "../../data/reporting-categories"; import { volunteerCustomHomesAccountMappings } from "../../data/account-mappings";
import { AppearanceSettings } from "../../components/app/appearance-settings";

export default function SettingsPage(){const categoryMap=new Map(compassReportingCategories.map(category=>[category.id,category]));const mappingMap=new Map(volunteerCustomHomesAccountMappings.map(mapping=>[mapping.glAccountId,mapping.reportingCategoryId]));const rows=volunteerCustomHomesGLAccounts.map(account=>{const category=categoryMap.get(mappingMap.get(account.id)??"");return [<span key={account.id}><strong className="block text-slate-900">{account.accountNumber} · {account.accountName}</strong><span className="text-xs text-slate-400">{account.accountType}</span></span>,category?.name??"Unmapped",category?.majorCategory??"—",<StatusBadge key={`${account.id}-status`} tone={category?"green":"amber"}>{category?"Mapped":"Unmapped"}</StatusBadge>,<select key={`${account.id}-select`} aria-label={`Assign category for ${account.accountName}`} defaultValue={category?.id??""} className="rounded-lg border border-slate-200 bg-white px-2 py-1.5 text-xs"><option value="">Choose category</option>{compassReportingCategories.map(option=><option key={option.id} value={option.id}>{option.name}</option>)}</select>];});return <PageShell><PageHeader eyebrow="Administration" title="Settings" description="Manage reporting preferences and understand how accounting data is organized in Compass." />
  <AppearanceSettings />
  <div className="mt-7 grid gap-6 lg:grid-cols-3"><Panel title="Company profile"><div className="p-5"><Building2 className="size-5 text-brand-700"/><p className="mt-3 font-semibold text-slate-950">{volunteerCustomHomes.name}</p><p className="mt-1 text-sm text-slate-500">{volunteerCustomHomes.legalName}</p><dl className="mt-5 space-y-3 text-sm"><div className="flex justify-between"><dt className="text-slate-500">Industry</dt><dd>{volunteerCustomHomes.industry}</dd></div><div className="flex justify-between"><dt className="text-slate-500">Fiscal year end</dt><dd>December</dd></div><div className="flex justify-between"><dt className="text-slate-500">Accounting system</dt><dd>{volunteerCustomHomes.accountingSystem}</dd></div></dl></div></Panel><Panel title="Reporting preferences"><div className="space-y-4 p-5"><label className="block text-sm font-medium text-slate-700">Default period<select className="mt-2 w-full rounded-lg border border-slate-200 bg-white p-2.5 text-sm"><option>Latest available month</option><option>Rolling 12 months</option></select></label><label className="block text-sm font-medium text-slate-700">Default analysis view<select className="mt-2 w-full rounded-lg border border-slate-200 bg-white p-2.5 text-sm"><option>R12M</option><option>Monthly</option><option>YTD</option></select></label><p className="text-xs leading-5 text-slate-400">Prototype controls only; preferences are not persisted yet.</p></div></Panel><Panel title="Data connection"><div className="p-5"><Unplug className="size-5 text-amber-600"/><p className="mt-3 font-semibold text-slate-900">QuickBooks Online not connected</p><p className="mt-2 text-sm leading-6 text-slate-500">This prototype uses approved modeling records. Authentication and external writes are not implemented.</p><button disabled className="mt-4 rounded-lg bg-slate-100 px-3 py-2 text-xs font-semibold text-slate-400">Connect QuickBooks · unavailable</button></div></Panel></div>
  <Panel title="How Compass organizes financial data" description="GL accounts → grouped reporting categories → major categories" className="mt-6"><div className="grid gap-4 p-5 md:grid-cols-3"><div className="rounded-xl bg-slate-50 p-4"><Database className="size-5 text-slate-500"/><h3 className="mt-3 text-sm font-semibold">GL accounts</h3><p className="mt-2 text-xs leading-5 text-slate-500">Original account numbers and names from the accounting system.</p></div><div className="rounded-xl bg-brand-50 p-4"><Layers3 className="size-5 text-brand-700"/><h3 className="mt-3 text-sm font-semibold">Reporting categories</h3><p className="mt-2 text-xs leading-5 text-slate-600">Consistent groups such as Labor, Materials, Fuel, and Office Payroll.</p></div><div className="rounded-xl bg-slate-100 p-4"><CheckCircle2 className="size-5 text-slate-600"/><h3 className="mt-3 text-sm font-semibold">Major categories</h3><p className="mt-2 text-xs leading-5 text-slate-600">Revenue, Direct Costs, Indirect Costs, Overhead, and Other Income/Expense.</p></div></div></Panel>
  <Panel title="Account mapping" description={`${volunteerCustomHomesAccountMappings.length} of ${volunteerCustomHomesGLAccounts.length} accounts mapped · assignment controls are prototype-only`} className="mt-6"><DataTable headers={["GL account","Reporting category","Major category","Status","Assignment"]} rows={rows}/></Panel>
  <Panel title="Financial categories" description="Default Compass categories used across financial reporting." className="mt-6"><div className="grid gap-3 p-5 sm:grid-cols-2 lg:grid-cols-3">{compassReportingCategories.map(category=><div key={category.id} className="rounded-xl border border-slate-200 p-4"><div className="flex items-center justify-between"><p className="text-sm font-semibold text-slate-900">{category.name}</p><StatusBadge tone="blue">Default</StatusBadge></div><p className="mt-2 text-xs text-slate-500">{category.majorCategory} · order {category.sortOrder}</p></div>)}</div></Panel>
  </PageShell>}
