import { Banknote, CircleGauge, Scale } from "lucide-react";
import { PageShell } from "../../components/app/page-shell";
import { PageHeader } from "../../components/app/page-header";
import { Panel, PrototypeBadge, StatCard } from "../../components/app/ui";
import { LineChart } from "../../components/app/line-chart";
import { liquidityFixture } from "../../data/prototype-fixtures";
import { formatDollarAbbreviation } from "../../lib/formatters/financial";

export default function CashPage(){const data=liquidityFixture;return <PageShell><PageHeader eyebrow="Liquidity" title="Cash & Working Capital" description="See the near-term resources available to fund active jobs and upcoming obligations."><PrototypeBadge /></PageHeader>
<div className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-3"><StatCard label="Cash balance" value={formatDollarAbbreviation(data.cash)} detail="Approved prototype cash position" icon={Banknote} tone="blue"/><StatCard label="Working capital" value={formatDollarAbbreviation(data.workingCapital)} detail="Current assets less current liabilities" icon={Scale}/><StatCard label="Current ratio" value={`${data.currentRatio.toFixed(2)}×`} detail="Liquidity coverage" icon={CircleGauge} tone="green"/></div>
<div className="mt-6 grid gap-6 xl:grid-cols-2"><Panel title="Monthly ending cash balance" description="Period-ending fixture balance for each month — not an R12M value and not calculated by the income-statement engine."><LineChart values={data.cashTrend} labels={data.cashTrendLabels.map(label=>`${label} 2026`)} format="currency" metricName="Ending cash balance" tooltipPrefix="Period ending" /></Panel><Panel title="Liquidity composition" description="Current assets and current liabilities"><div className="grid gap-6 p-5 sm:grid-cols-2"><div><h3 className="text-xs font-semibold uppercase tracking-wide text-slate-500">Current assets</h3>{data.currentAssets.map(item=><div key={item.label} className="mt-4 flex justify-between text-sm"><span className="text-slate-600">{item.label}</span><strong>{formatDollarAbbreviation(item.amount)}</strong></div>)}</div><div><h3 className="text-xs font-semibold uppercase tracking-wide text-slate-500">Current liabilities</h3>{data.currentLiabilities.map(item=><div key={item.label} className="mt-4 flex justify-between text-sm"><span className="text-slate-600">{item.label}</span><strong>{formatDollarAbbreviation(item.amount)}</strong></div>)}</div></div></Panel></div>
<Panel title="Liquidity priorities" className="mt-6"><div className="grid gap-4 p-5 md:grid-cols-3"><p className="rounded-xl bg-amber-50 p-4 text-sm leading-6 text-amber-900">Collections are the fastest liquidity lever: Accounts Receivable is nearly twice the current cash balance.</p><p className="rounded-xl bg-blue-50 p-4 text-sm leading-6 text-blue-900">Sequence vendor payments around customer receipts to avoid drawing cash below operating needs.</p><p className="rounded-xl bg-slate-50 p-4 text-sm leading-6 text-slate-700">The current ratio is positive, but a meaningful share of coverage depends on timely AR conversion.</p></div></Panel></PageShell>}
